name: itsBREX
favicon: null
layout_spectrum: 0.18152
typography_spectrum: 0.1474
title: BREX (Official)
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfcfa'
    - '#739cd2'
    - '#88725d'
    - '#120a05'
    - '#b4bac6'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
