name: itsBREX
favicon: null
layout_spectrum: 0.95923
typography_spectrum: 0.1474
title: BREX (Official)
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#241b14'
    - '#84929b'
    - '#ebe9ea'
    - '#b7b1b1'
    - '#7f7169'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
