name: Brian
favicon: null
layout_spectrum: 0.2473442442715168
typography_spectrum: 0.46699566510505974
title: BREX (Official) site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9922070330940187
  lightness: 0.5442169713787735
  saturation: 0.28392629721201956
  rhythmicContrast: 0.23251901543699205
purpose: []
